import { sql } from 'drizzle-orm';
import {
  CONCRETE_STRENGTHS,
  CONTACT_METHODS,
  CUSTOMER_TYPES,
  LOCALES,
  PREFERRED_TIMES,
  PROJECT_TYPES,
  QUOTE_STATUSES,
  TRI_STATES,
} from '@/lib/quote-options';
import {
  bigint,
  boolean,
  date,
  integer,
  index,
  jsonb,
  numeric,
  pgEnum,
  pgSequence,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/* -------------------------------------------------------------------------- */
/* Enums                                                                       */
/* -------------------------------------------------------------------------- */
/*
 * Values come from `@/lib/quote-options`, which the Zod validation and the form
 * UI also read, so an option can never exist in one layer and not another.
 * They are locale-independent codes; their labels live in the dictionaries.
 */

export const localeEnum = pgEnum('locale', LOCALES);

export const customerTypeEnum = pgEnum('customer_type', CUSTOMER_TYPES);

export const contactMethodEnum = pgEnum('contact_method', CONTACT_METHODS);

export const projectTypeEnum = pgEnum('project_type', PROJECT_TYPES);

export const concreteStrengthEnum = pgEnum('concrete_strength', CONCRETE_STRENGTHS);

/** Yes / No / I don't know — customers must never be forced to guess. */
export const triStateEnum = pgEnum('tri_state', TRI_STATES);

export const preferredTimeEnum = pgEnum('preferred_time', PREFERRED_TIMES);

export const quoteStatusEnum = pgEnum('quote_status', QUOTE_STATUSES);

export const qualificationStatusEnum = pgEnum('qualification_status', [
  'PENDING',
  'QUALIFIED',
  'DISQUALIFIED',
]);

export const googleAdsGranularityEnum = pgEnum('google_ads_granularity', ['CAMPAIGN', 'AD_GROUP']);

export const googleAdsSyncStatusEnum = pgEnum('google_ads_sync_status', [
  'PENDING',
  'RUNNING',
  'SUCCEEDED',
  'PARTIALLY_FAILED',
  'FAILED',
]);

export const offlineConversionStageEnum = pgEnum('offline_conversion_stage', [
  'QUALIFIED_LEAD',
  'WON_JOB',
]);

export const offlineConversionStatusEnum = pgEnum('offline_conversion_status', [
  'PENDING',
  'PROCESSING',
  'UPLOADED',
  'RETRY',
  'PERMANENTLY_FAILED',
  'SKIPPED',
]);

export const supplierStatusEnum = pgEnum('supplier_status', [
  'PROSPECT',
  'ONBOARDING',
  'ACTIVE',
  'PAUSED',
  'INACTIVE',
]);

export const supplierApplicationStatusEnum = pgEnum('supplier_application_status', [
  'NEW',
  'CONTACTED',
  'QUALIFIED',
  'APPROVED',
  'REJECTED',
]);

export const supplierAssignmentStatusEnum = pgEnum('supplier_assignment_status', [
  'PENDING',
  'VIEWED',
  'INTERESTED',
  'QUOTED',
  'ACCEPTED',
  'DECLINED',
  'EXPIRED',
  'WON',
  'LOST',
]);

export const adConsentEnum = pgEnum('ad_consent', ['GRANTED', 'DENIED', 'UNKNOWN']);

/* -------------------------------------------------------------------------- */
/* Human-readable reference                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Feeds the customer-facing reference (BD-000123).
 *
 * The sequential number is deliberately *not* the security identifier: the
 * primary key is a UUID, and nothing addressable is derivable from a reference
 * number. `public_id` is a stored generated column so the database — not the
 * application — guarantees uniqueness and format under concurrent inserts.
 */
export const quoteReferenceSeq = pgSequence('quote_reference_seq', {
  startWith: 1,
  increment: 1,
});

/* -------------------------------------------------------------------------- */
/* quote_requests                                                              */
/* -------------------------------------------------------------------------- */

export const quoteRequests = pgTable(
  'quote_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    referenceNumber: bigint('reference_number', { mode: 'number' })
      .notNull()
      .default(sql`nextval('quote_reference_seq')`),

    /** e.g. "BD-000123". Generated by Postgres from `reference_number`. */
    publicId: text('public_id')
      .notNull()
      .generatedAlwaysAs(sql`'BD-' || lpad(reference_number::text, 6, '0')`),

    /** Language the request was submitted in — drives reply language. */
    locale: localeEnum('locale').notNull().default('fr'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),

    /* ---- Customer ------------------------------------------------------- */
    customerType: customerTypeEnum('customer_type').notNull(),
    name: varchar('name', { length: 120 }).notNull(),
    companyName: varchar('company_name', { length: 160 }),
    email: varchar('email', { length: 254 }).notNull(),
    phone: varchar('phone', { length: 32 }).notNull(),
    preferredContactMethod: contactMethodEnum('preferred_contact_method').notNull(),

    /* ---- Location ------------------------------------------------------- */
    address: varchar('address', { length: 240 }).notNull(),
    city: varchar('city', { length: 120 }).notNull(),
    postalCode: varchar('postal_code', { length: 12 }).notNull(),
    accessNotes: text('access_notes'),

    /* ---- Project -------------------------------------------------------- */
    projectType: projectTypeEnum('project_type').notNull(),

    /** Null whenever `volumeUnknown` is true. */
    estimatedVolumeM3: numeric('estimated_volume_m3', { precision: 7, scale: 2 }),
    volumeUnknown: boolean('volume_unknown').notNull().default(false),

    concreteStrength: concreteStrengthEnum('concrete_strength').notNull().default('UNKNOWN'),

    pumpRequired: triStateEnum('pump_required').notNull().default('UNKNOWN'),
    pumpNotes: text('pump_notes'),

    /* ---- Schedule ------------------------------------------------------- */
    desiredDate: date('desired_date').notNull(),
    preferredTime: preferredTimeEnum('preferred_time'),
    scheduleFlexible: boolean('schedule_flexible').notNull().default(false),

    additionalNotes: text('additional_notes'),

    /* ---- Attribution ---------------------------------------------------- */
    gclid: varchar('gclid', { length: 256 }),
    msclkid: varchar('msclkid', { length: 256 }),
    fbclid: varchar('fbclid', { length: 256 }),
    utmSource: varchar('utm_source', { length: 120 }),
    utmMedium: varchar('utm_medium', { length: 120 }),
    utmCampaign: varchar('utm_campaign', { length: 160 }),
    utmTerm: varchar('utm_term', { length: 160 }),
    utmContent: varchar('utm_content', { length: 160 }),
    referrer: varchar('referrer', { length: 512 }),
    landingPage: varchar('landing_page', { length: 512 }),
    firstTouchSource: varchar('first_touch_source', { length: 120 }),
    firstTouchMedium: varchar('first_touch_medium', { length: 120 }),
    firstTouchCampaign: varchar('first_touch_campaign', { length: 160 }),
    firstTouchTerm: varchar('first_touch_term', { length: 160 }),
    firstTouchContent: varchar('first_touch_content', { length: 160 }),
    firstTouchLandingPage: varchar('first_touch_landing_page', { length: 512 }),
    firstTouchReferrer: varchar('first_touch_referrer', { length: 512 }),
    firstTouchTimestamp: timestamp('first_touch_timestamp', { withTimezone: true }),
    lastTouchSource: varchar('last_touch_source', { length: 120 }),
    lastTouchMedium: varchar('last_touch_medium', { length: 120 }),
    lastTouchCampaign: varchar('last_touch_campaign', { length: 160 }),
    lastTouchTerm: varchar('last_touch_term', { length: 160 }),
    lastTouchContent: varchar('last_touch_content', { length: 160 }),
    lastTouchLandingPage: varchar('last_touch_landing_page', { length: 512 }),
    lastTouchReferrer: varchar('last_touch_referrer', { length: 512 }),
    lastTouchTimestamp: timestamp('last_touch_timestamp', { withTimezone: true }),
    quoteEntryPage: varchar('quote_entry_page', { length: 512 }),
    submissionPage: varchar('submission_page', { length: 512 }),
    deviceCategory: varchar('device_category', { length: 16 }),
    browserLanguage: varchar('browser_language', { length: 80 }),

    /* ---- Internal ------------------------------------------------------- */
    /* Never selected into anything that reaches the public site. */
    abuseStatus: varchar('abuse_status', { length: 32 }).notNull().default('clean'),
    sourceIpHash: varchar('source_ip_hash', { length: 64 }),
    duplicateFingerprint: varchar('duplicate_fingerprint', { length: 64 }),
    status: quoteStatusEnum('status').notNull().default('NEW'),
    qualificationStatus: qualificationStatusEnum('qualification_status')
      .notNull()
      .default('PENDING'),
    qualifiedAt: timestamp('qualified_at', { withTimezone: true }),
    qualifiedBy: varchar('qualified_by', { length: 120 }),
    qualificationReason: text('qualification_reason'),
    disqualificationReason: varchar('disqualification_reason', { length: 80 }),
    firstResponseAt: timestamp('first_response_at', { withTimezone: true }),
    firstContactAt: timestamp('first_contact_at', { withTimezone: true }),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    wonAt: timestamp('won_at', { withTimezone: true }),
    lostAt: timestamp('lost_at', { withTimezone: true }),
    estimatedJobValueCad: numeric('estimated_job_value_cad', { precision: 12, scale: 2 }),
    finalJobValueCad: numeric('final_job_value_cad', { precision: 12, scale: 2 }),
    betondispoRevenueCad: numeric('betondispo_revenue_cad', { precision: 12, scale: 2 }),
    supplierSelected: varchar('supplier_selected', { length: 160 }),
    serviceDate: date('service_date'),
    adUserDataConsent: adConsentEnum('ad_user_data_consent').notNull().default('UNKNOWN'),
    adPersonalizationConsent: adConsentEnum('ad_personalization_consent')
      .notNull()
      .default('UNKNOWN'),
    consentCapturedAt: timestamp('consent_captured_at', { withTimezone: true }),
    consentSource: varchar('consent_source', { length: 80 }),
    internalNotes: text('internal_notes'),
    lostReason: text('lost_reason'),
  },
  (table) => [
    index('quote_requests_created_at_idx').on(table.createdAt.desc()),
    index('quote_requests_status_idx').on(table.status),
    index('quote_requests_qualification_status_idx').on(table.qualificationStatus),
    index('quote_requests_qualified_at_idx').on(table.qualifiedAt),
    index('quote_requests_city_idx').on(table.city),
    index('quote_requests_desired_date_idx').on(table.desiredDate),
    index('quote_requests_customer_type_idx').on(table.customerType),
    index('quote_requests_gclid_idx').on(table.gclid),
    index('quote_requests_first_touch_source_idx').on(table.firstTouchSource),
    index('quote_requests_first_touch_landing_page_idx').on(table.firstTouchLandingPage),
    index('quote_requests_last_touch_source_idx').on(table.lastTouchSource),
    index('quote_requests_quote_entry_page_idx').on(table.quoteEntryPage),
    index('quote_requests_first_response_at_idx').on(table.firstResponseAt),
    index('quote_requests_won_at_idx').on(table.wonAt),
    index('quote_requests_source_ip_hash_idx').on(table.sourceIpHash),
    index('quote_requests_duplicate_fingerprint_idx').on(table.duplicateFingerprint),
  ],
);

export type QuoteRequest = typeof quoteRequests.$inferSelect;
export type NewQuoteRequest = typeof quoteRequests.$inferInsert;

/* -------------------------------------------------------------------------- */
/* quote_request_events                                                       */
/* -------------------------------------------------------------------------- */

export const quoteRequestEvents = pgTable(
  'quote_request_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteRequestId: uuid('quote_request_id')
      .notNull()
      .references(() => quoteRequests.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    actor: varchar('actor', { length: 40 }).notNull().default('system'),
    type: varchar('type', { length: 80 }).notNull(),
    message: text('message').notNull(),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
  },
  (table) => [
    index('quote_request_events_request_created_idx').on(table.quoteRequestId, table.createdAt),
    index('quote_request_events_type_idx').on(table.type),
  ],
);

export type QuoteRequestEvent = typeof quoteRequestEvents.$inferSelect;
export type NewQuoteRequestEvent = typeof quoteRequestEvents.$inferInsert;

/* -------------------------------------------------------------------------- */
/* Google Ads reporting                                                        */
/* -------------------------------------------------------------------------- */

export const googleAdsDailyPerformance = pgTable(
  'google_ads_daily_performance',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: varchar('customer_id', { length: 32 }).notNull(),
    reportDate: date('report_date').notNull(),
    granularity: googleAdsGranularityEnum('granularity').notNull().default('CAMPAIGN'),
    performanceKey: text('performance_key').notNull(),
    campaignId: varchar('campaign_id', { length: 32 }).notNull(),
    campaignName: varchar('campaign_name', { length: 255 }).notNull(),
    campaignStatus: varchar('campaign_status', { length: 40 }),
    campaignType: varchar('campaign_type', { length: 80 }),
    adGroupId: varchar('ad_group_id', { length: 32 }),
    adGroupName: varchar('ad_group_name', { length: 255 }),
    currencyCode: varchar('currency_code', { length: 8 }).notNull().default('CAD'),
    impressions: integer('impressions').notNull().default(0),
    clicks: integer('clicks').notNull().default(0),
    costMicros: bigint('cost_micros', { mode: 'number' }).notNull().default(0),
    conversions: numeric('conversions', { precision: 12, scale: 4 }).notNull().default('0'),
    conversionValue: numeric('conversion_value', { precision: 14, scale: 4 })
      .notNull()
      .default('0'),
    allConversions: numeric('all_conversions', { precision: 12, scale: 4 }).notNull().default('0'),
    allConversionValue: numeric('all_conversion_value', { precision: 14, scale: 4 })
      .notNull()
      .default('0'),
    interactions: integer('interactions'),
    syncedAt: timestamp('synced_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex('google_ads_daily_unique_idx').on(table.performanceKey),
    index('google_ads_daily_report_date_idx').on(table.reportDate),
    index('google_ads_daily_campaign_idx').on(table.campaignId),
    index('google_ads_daily_customer_date_idx').on(table.customerId, table.reportDate),
  ],
);

export const googleAdsSyncRuns = pgTable(
  'google_ads_sync_runs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    status: googleAdsSyncStatusEnum('status').notNull().default('PENDING'),
    rowsReceived: integer('rows_received').notNull().default(0),
    rowsUpserted: integer('rows_upserted').notNull().default(0),
    apiCalls: integer('api_calls').notNull().default(0),
    errorCode: varchar('error_code', { length: 120 }),
    sanitizedError: text('sanitized_error'),
    initiatedBy: varchar('initiated_by', { length: 80 }).notNull().default('admin'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('google_ads_sync_runs_started_idx').on(table.startedAt.desc()),
    index('google_ads_sync_runs_status_idx').on(table.status),
  ],
);

export const googleAdsOfflineConversions = pgTable(
  'google_ads_offline_conversions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteRequestId: uuid('quote_request_id')
      .notNull()
      .references(() => quoteRequests.id, { onDelete: 'cascade' }),
    requestNumber: varchar('request_number', { length: 32 }).notNull(),
    conversionStage: offlineConversionStageEnum('conversion_stage').notNull(),
    conversionActionId: varchar('conversion_action_id', { length: 64 }),
    conversionActionResourceName: varchar('conversion_action_resource_name', { length: 255 }),
    gclid: varchar('gclid', { length: 256 }),
    gbraid: varchar('gbraid', { length: 256 }),
    wbraid: varchar('wbraid', { length: 256 }),
    orderId: varchar('order_id', { length: 80 }).notNull(),
    conversionDateTime: timestamp('conversion_date_time', { withTimezone: true }).notNull(),
    conversionValue: numeric('conversion_value', { precision: 12, scale: 2 })
      .notNull()
      .default('0'),
    currencyCode: varchar('currency_code', { length: 8 }).notNull().default('CAD'),
    valueStrategy: varchar('value_strategy', { length: 80 }).notNull().default('fixed'),
    consentAdUserData: adConsentEnum('consent_ad_user_data').notNull().default('UNKNOWN'),
    consentAdPersonalization: adConsentEnum('consent_ad_personalization')
      .notNull()
      .default('UNKNOWN'),
    uploadStatus: offlineConversionStatusEnum('upload_status').notNull().default('PENDING'),
    attemptCount: integer('attempt_count').notNull().default(0),
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }),
    googleJobId: varchar('google_job_id', { length: 120 }),
    googleErrorCode: varchar('google_error_code', { length: 120 }),
    sanitizedError: text('sanitized_error'),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true }),
    lastAttemptAt: timestamp('last_attempt_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex('google_ads_offline_order_id_idx').on(table.orderId),
    uniqueIndex('google_ads_offline_stage_request_idx').on(
      table.conversionStage,
      table.quoteRequestId,
    ),
    index('google_ads_offline_status_next_idx').on(table.uploadStatus, table.nextAttemptAt),
    index('google_ads_offline_quote_idx').on(table.quoteRequestId),
  ],
);

export type GoogleAdsDailyPerformance = typeof googleAdsDailyPerformance.$inferSelect;
export type NewGoogleAdsDailyPerformance = typeof googleAdsDailyPerformance.$inferInsert;
export type GoogleAdsSyncRun = typeof googleAdsSyncRuns.$inferSelect;
export type NewGoogleAdsSyncRun = typeof googleAdsSyncRuns.$inferInsert;
export type GoogleAdsOfflineConversion = typeof googleAdsOfflineConversions.$inferSelect;
export type NewGoogleAdsOfflineConversion = typeof googleAdsOfflineConversions.$inferInsert;

/* -------------------------------------------------------------------------- */
/* Supplier applications                                                       */
/* -------------------------------------------------------------------------- */

export const supplierApplicationReferenceSeq = pgSequence('supplier_application_reference_seq', {
  startWith: 1,
  increment: 1,
});

export const supplierApplications = pgTable(
  'supplier_applications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    referenceNumber: bigint('reference_number', { mode: 'number' })
      .notNull()
      .default(sql`nextval('supplier_application_reference_seq')`),
    publicId: text('public_id')
      .notNull()
      .generatedAlwaysAs(sql`'BP-' || lpad(reference_number::text, 6, '0')`),
    locale: localeEnum('locale').notNull().default('fr'),
    status: supplierApplicationStatusEnum('status').notNull().default('NEW'),

    companyName: varchar('company_name', { length: 160 }).notNull(),
    contactName: varchar('contact_name', { length: 120 }).notNull(),
    email: varchar('email', { length: 254 }).notNull(),
    phone: varchar('phone', { length: 32 }).notNull(),
    website: varchar('website', { length: 255 }),
    serviceAreaText: varchar('service_area_text', { length: 500 }).notNull(),
    services: jsonb('services')
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    message: text('message'),

    landingPage: varchar('landing_page', { length: 512 }),
    referrer: varchar('referrer', { length: 512 }),
    gclid: varchar('gclid', { length: 256 }),
    msclkid: varchar('msclkid', { length: 256 }),
    fbclid: varchar('fbclid', { length: 256 }),
    utmSource: varchar('utm_source', { length: 120 }),
    utmMedium: varchar('utm_medium', { length: 120 }),
    utmCampaign: varchar('utm_campaign', { length: 160 }),
    utmTerm: varchar('utm_term', { length: 160 }),
    utmContent: varchar('utm_content', { length: 160 }),
    firstTouchSource: varchar('first_touch_source', { length: 120 }),
    firstTouchMedium: varchar('first_touch_medium', { length: 120 }),
    firstTouchCampaign: varchar('first_touch_campaign', { length: 160 }),
    firstTouchTerm: varchar('first_touch_term', { length: 160 }),
    firstTouchContent: varchar('first_touch_content', { length: 160 }),
    firstTouchLandingPage: varchar('first_touch_landing_page', { length: 512 }),
    firstTouchReferrer: varchar('first_touch_referrer', { length: 512 }),
    firstTouchTimestamp: timestamp('first_touch_timestamp', { withTimezone: true }),
    lastTouchSource: varchar('last_touch_source', { length: 120 }),
    lastTouchMedium: varchar('last_touch_medium', { length: 120 }),
    lastTouchCampaign: varchar('last_touch_campaign', { length: 160 }),
    lastTouchTerm: varchar('last_touch_term', { length: 160 }),
    lastTouchContent: varchar('last_touch_content', { length: 160 }),
    lastTouchLandingPage: varchar('last_touch_landing_page', { length: 512 }),
    lastTouchReferrer: varchar('last_touch_referrer', { length: 512 }),
    lastTouchTimestamp: timestamp('last_touch_timestamp', { withTimezone: true }),
    submissionPage: varchar('submission_page', { length: 512 }),
    deviceCategory: varchar('device_category', { length: 16 }),
    browserLanguage: varchar('browser_language', { length: 80 }),

    abuseStatus: varchar('abuse_status', { length: 32 }).notNull().default('clean'),
    sourceIpHash: varchar('source_ip_hash', { length: 64 }),
    duplicateFingerprint: varchar('duplicate_fingerprint', { length: 64 }),
    internalNotes: text('internal_notes'),
    firstContactedAt: timestamp('first_contacted_at', { withTimezone: true }),
    qualifiedAt: timestamp('qualified_at', { withTimezone: true }),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    rejectedAt: timestamp('rejected_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index('supplier_applications_created_at_idx').on(table.createdAt.desc()),
    index('supplier_applications_status_idx').on(table.status),
    index('supplier_applications_email_idx').on(table.email),
    index('supplier_applications_company_idx').on(table.companyName),
    index('supplier_applications_source_idx').on(table.firstTouchSource),
    index('supplier_applications_duplicate_fingerprint_idx').on(table.duplicateFingerprint),
    index('supplier_applications_source_ip_hash_idx').on(table.sourceIpHash),
  ],
);

export type SupplierApplication = typeof supplierApplications.$inferSelect;
export type NewSupplierApplication = typeof supplierApplications.$inferInsert;

/* -------------------------------------------------------------------------- */
/* Suppliers                                                                   */
/* -------------------------------------------------------------------------- */

export const suppliers = pgTable(
  'suppliers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: varchar('name', { length: 160 }).notNull(),
    legalName: varchar('legal_name', { length: 200 }),
    email: varchar('email', { length: 254 }).notNull(),
    phone: varchar('phone', { length: 32 }),
    status: supplierStatusEnum('status').notNull().default('PROSPECT'),
    serviceAreas: jsonb('service_areas').$type<string[]>(),
    projectCapabilities: jsonb('project_capabilities').$type<string[]>(),
    minimumVolumeM3: numeric('minimum_volume_m3', { precision: 7, scale: 2 }),
    maximumVolumeM3: numeric('maximum_volume_m3', { precision: 7, scale: 2 }),
    pumpAvailable: boolean('pump_available'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index('suppliers_status_idx').on(table.status),
    uniqueIndex('suppliers_email_idx').on(table.email),
  ],
);

export const supplierAssignments = pgTable(
  'supplier_assignments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteRequestId: uuid('quote_request_id')
      .notNull()
      .references(() => quoteRequests.id, { onDelete: 'cascade' }),
    supplierId: uuid('supplier_id')
      .notNull()
      .references(() => suppliers.id, { onDelete: 'cascade' }),
    assignedAt: timestamp('assigned_at', { withTimezone: true }).notNull().defaultNow(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    viewedAt: timestamp('viewed_at', { withTimezone: true }),
    respondedAt: timestamp('responded_at', { withTimezone: true }),
    responseStatus: supplierAssignmentStatusEnum('response_status').notNull().default('PENDING'),
    quotedAmount: numeric('quoted_amount', { precision: 12, scale: 2 }),
    supplierMessage: text('supplier_message'),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    declinedAt: timestamp('declined_at', { withTimezone: true }),
    declineReason: varchar('decline_reason', { length: 255 }),
    wonAt: timestamp('won_at', { withTimezone: true }),
    lostAt: timestamp('lost_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex('supplier_assignments_unique_idx').on(table.quoteRequestId, table.supplierId),
    index('supplier_assignments_supplier_idx').on(table.supplierId),
    index('supplier_assignments_quote_idx').on(table.quoteRequestId),
    index('supplier_assignments_status_idx').on(table.responseStatus),
  ],
);

export type Supplier = typeof suppliers.$inferSelect;
export type NewSupplier = typeof suppliers.$inferInsert;
export type SupplierAssignment = typeof supplierAssignments.$inferSelect;
export type NewSupplierAssignment = typeof supplierAssignments.$inferInsert;
