import { sql } from 'drizzle-orm';
import {
  CONCRETE_STRENGTHS,
  CONTACT_METHODS,
  CUSTOMER_TYPES,
  LOCALES,
  PREFERRED_TIMES,
  PROJECT_TYPES,
  QUOTE_STATUSES,
  TRI_STATES,
} from '@/lib/quote-options';
import {
  bigint,
  boolean,
  date,
  index,
  numeric,
  pgEnum,
  pgSequence,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/* -------------------------------------------------------------------------- */
/* Enums                                                                       */
/* -------------------------------------------------------------------------- */
/*
 * Values come from `@/lib/quote-options`, which the Zod validation and the form
 * UI also read, so an option can never exist in one layer and not another.
 * They are locale-independent codes; their labels live in the dictionaries.
 */

export const localeEnum = pgEnum('locale', LOCALES);

export const customerTypeEnum = pgEnum('customer_type', CUSTOMER_TYPES);

export const contactMethodEnum = pgEnum('contact_method', CONTACT_METHODS);

export const projectTypeEnum = pgEnum('project_type', PROJECT_TYPES);

export const concreteStrengthEnum = pgEnum('concrete_strength', CONCRETE_STRENGTHS);

/** Yes / No / I don't know — customers must never be forced to guess. */
export const triStateEnum = pgEnum('tri_state', TRI_STATES);

export const preferredTimeEnum = pgEnum('preferred_time', PREFERRED_TIMES);

export const quoteStatusEnum = pgEnum('quote_status', QUOTE_STATUSES);

/* -------------------------------------------------------------------------- */
/* Human-readable reference                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Feeds the customer-facing reference (BD-000123).
 *
 * The sequential number is deliberately *not* the security identifier: the
 * primary key is a UUID, and nothing addressable is derivable from a reference
 * number. `public_id` is a stored generated column so the database — not the
 * application — guarantees uniqueness and format under concurrent inserts.
 */
export const quoteReferenceSeq = pgSequence('quote_reference_seq', {
  startWith: 1,
  increment: 1,
});

/* -------------------------------------------------------------------------- */
/* quote_requests                                                              */
/* -------------------------------------------------------------------------- */

export const quoteRequests = pgTable(
  'quote_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    referenceNumber: bigint('reference_number', { mode: 'number' })
      .notNull()
      .default(sql`nextval('quote_reference_seq')`),

    /** e.g. "BD-000123". Generated by Postgres from `reference_number`. */
    publicId: text('public_id')
      .notNull()
      .generatedAlwaysAs(sql`'BD-' || lpad(reference_number::text, 6, '0')`),

    /** Language the request was submitted in — drives reply language. */
    locale: localeEnum('locale').notNull().default('fr'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),

    /* ---- Customer ------------------------------------------------------- */
    customerType: customerTypeEnum('customer_type').notNull(),
    name: varchar('name', { length: 120 }).notNull(),
    companyName: varchar('company_name', { length: 160 }),
    email: varchar('email', { length: 254 }).notNull(),
    phone: varchar('phone', { length: 32 }).notNull(),
    preferredContactMethod: contactMethodEnum('preferred_contact_method').notNull(),

    /* ---- Location ------------------------------------------------------- */
    address: varchar('address', { length: 240 }).notNull(),
    city: varchar('city', { length: 120 }).notNull(),
    postalCode: varchar('postal_code', { length: 12 }).notNull(),
    accessNotes: text('access_notes'),

    /* ---- Project -------------------------------------------------------- */
    projectType: projectTypeEnum('project_type').notNull(),

    /** Null whenever `volumeUnknown` is true. */
    estimatedVolumeM3: numeric('estimated_volume_m3', { precision: 7, scale: 2 }),
    volumeUnknown: boolean('volume_unknown').notNull().default(false),

    concreteStrength: concreteStrengthEnum('concrete_strength').notNull().default('UNKNOWN'),

    pumpRequired: triStateEnum('pump_required').notNull().default('UNKNOWN'),
    pumpNotes: text('pump_notes'),

    /* ---- Schedule ------------------------------------------------------- */
    desiredDate: date('desired_date').notNull(),
    preferredTime: preferredTimeEnum('preferred_time'),
    scheduleFlexible: boolean('schedule_flexible').notNull().default(false),

    additionalNotes: text('additional_notes'),

    /* ---- Attribution ---------------------------------------------------- */
    utmSource: varchar('utm_source', { length: 120 }),
    utmMedium: varchar('utm_medium', { length: 120 }),
    utmCampaign: varchar('utm_campaign', { length: 160 }),
    utmTerm: varchar('utm_term', { length: 160 }),
    utmContent: varchar('utm_content', { length: 160 }),
    referrer: varchar('referrer', { length: 512 }),
    landingPage: varchar('landing_page', { length: 512 }),

    /* ---- Internal ------------------------------------------------------- */
    /* Never selected into anything that reaches the public site. */
    abuseStatus: varchar('abuse_status', { length: 32 }).notNull().default('clean'),
    sourceIpHash: varchar('source_ip_hash', { length: 64 }),
    duplicateFingerprint: varchar('duplicate_fingerprint', { length: 64 }),
    status: quoteStatusEnum('status').notNull().default('NEW'),
    internalNotes: text('internal_notes'),
    lostReason: text('lost_reason'),
  },
  (table) => [
    index('quote_requests_created_at_idx').on(table.createdAt.desc()),
    index('quote_requests_status_idx').on(table.status),
    index('quote_requests_city_idx').on(table.city),
    index('quote_requests_desired_date_idx').on(table.desiredDate),
    index('quote_requests_customer_type_idx').on(table.customerType),
    index('quote_requests_source_ip_hash_idx').on(table.sourceIpHash),
    index('quote_requests_duplicate_fingerprint_idx').on(table.duplicateFingerprint),
  ],
);

export type QuoteRequest = typeof quoteRequests.$inferSelect;
export type NewQuoteRequest = typeof quoteRequests.$inferInsert;
